import { TabId, Column, RolePermission } from "./permission.types";

export const COLUMNS: Record<TabId, Column[]> = {
	"system-roles": [
		{ key: "role", label: "ROLE NAME", width: "200px" },
		{ key: "users", label: "USERS", align: "center", width: "100px" },
		{ key: "description", label: "DESCRIPTION" },
		{ key: "status", label: "STATUS", align: "center", width: "120px" },
		{ key: "lastModified", label: "LAST MODIFIED", width: "150px" },
	],
	feature: [
		{ key: "feature", label: "FEATURE", width: "500px" },
		{
			key: "systemAdmin",
			label: "SYSTEM ADMIN",
			align: "center",
			width: "250px",
		},
		{
			key: "groupAdmin",
			label: "GROUP ADMIN",
			align: "center",
			width: "250px",
		},
		{ key: "member", label: "MEMBER", align: "center", width: "250px" },
	],
	project: [
		{ key: "project", label: "PROJECT", width: "200px" },
		{ key: "owner", label: "OWNER", width: "180px" },
		{ key: "members", label: "MEMBERS", align: "center", width: "100px" },
		{ key: "access", label: "ACCESS LEVEL", width: "150px" },
		{ key: "lastActivity", label: "LAST ACTIVITY", width: "150px" },
	],
	"resource-limit": [
		{ key: "resource", label: "RESOURCE", width: "500px" },
		{
			key: "systemAdmin",
			label: "SYSTEM ADMIN",
			align: "center",
			width: "200px",
		},
		{
			key: "groupAdmin",
			label: "GROUP ADMIN",
			align: "center",
			width: "200px",
		},
		{ key: "member", label: "MEMBER", align: "center", width: "200px" },
	],
	"api-keys": [
		{ key: "service", label: "SERVICE", width: "500px" },
		{
			key: "systemAdmin",
			label: "SYSTEM ADMIN",
			align: "center",
			width: "200px",
		},
		{
			key: "groupAdmin",
			label: "GROUP ADMIN",
			align: "center",
			width: "200px",
		},
		{ key: "member", label: "MEMBER", align: "center", width: "200px" },
	],
	"code-execution": [
		{ key: "environment", label: "ENVIRONMENT", width: "200px" },
		{ key: "languages", label: "LANGUAGES", width: "200px" },
		{ key: "timeout", label: "TIMEOUT", align: "center", width: "120px" },
		{ key: "memory", label: "MEMORY LIMIT", align: "center", width: "140px" },
		{ key: "status", label: "STATUS", align: "center", width: "120px" },
	],
	security: [
		{ key: "setting", label: "SECURITY SETTING", width: "400px" },
		{ key: "value", label: "VALUE", width: "350px" },
		{ key: "scope", label: "SCOPE", width: "350px" },
		{ key: "enforced", label: "ENFORCED", align: "center", width: "200px" },
	],
	"change-history": [
		{ key: "time", label: "TIME", width: "180px" },
		{ key: "user", label: "USER", width: "200px" },
		{ key: "action", label: "ACTION", width: "200px" },
		{ key: "target", label: "TARGET", width: "200px" },
		{ key: "changes", label: "CHANGES" },
		{ key: "ip", label: "IP ADDRESS", width: "140px" },
	],
};

export const MOCK_DATA: Record<TabId, RolePermission[]> = {
	"system-roles": [
		{
			role: "System Admin",
			users: 3,
			description: "Description for System Admin role",
			status: "Active",
			lastModified: "2025-10-15 14:30",
		},
		{
			role: "Group Admin",
			users: 8,
			description: "Description for Group Admin role",
			status: "Active",
			lastModified: "2025-10-14 09:15",
		},
		{
			role: "Member",
			users: 1250,
			description: "Description for Member role",
			status: "Active",
			lastModified: "2025-10-10 08:00",
		},
	],
	feature: [
		{
			feature: "Real-time Chat",
			systemAdmin: true,
			groupAdmin: true,
			member: true,
		},
		{
			feature: "Code Execution",
			systemAdmin: true,
			groupAdmin: true,
			member: false,
		},
		{
			feature: "AI Assistant",
			systemAdmin: true,
			groupAdmin: true,
			member: false,
		},
		{
			feature: "GitHub Integration",
			systemAdmin: true,
			groupAdmin: false,
			member: false,
		},
		{
			feature: "Snippet Library",
			systemAdmin: true,
			groupAdmin: true,
			member: true,
		},
		{
			feature: "File Upload",
			systemAdmin: true,
			groupAdmin: true,
			member: true,
		},
	],
	project: [
		{
			project: "DevChat Platform",
			owner: "admin@devchat.com",
			members: 45,
			access: "Full Access",
			lastActivity: "2025-10-16 10:30",
		},
		{
			project: "API Gateway",
			owner: "tech@devchat.com",
			members: 12,
			access: "Read/Write",
			lastActivity: "2025-10-15 14:20",
		},
		{
			project: "Mobile App",
			owner: "mobile@devchat.com",
			members: 8,
			access: "Read Only",
			lastActivity: "2025-10-14 09:15",
		},
	],
	"resource-limit": [
		{
			resource: "Messages / Day",
			systemAdmin: "Unlimited",
			groupAdmin: "5,000",
			member: "2,000",
		},
		{
			resource: "Code Execution / Day",
			systemAdmin: "Unlimited",
			groupAdmin: "500",
			member: "100",
		},
		{
			resource: "AI Requests / Day",
			systemAdmin: "Unlimited",
			groupAdmin: "1,000",
			member: "100",
		},
		{
			resource: "File Upload Size",
			systemAdmin: "100 MB",
			groupAdmin: "50 MB",
			member: "10 MB",
		},
		{
			resource: "Total Storage",
			systemAdmin: "Unlimited",
			groupAdmin: "10 GB",
			member: "1 GB",
		},
		{
			resource: "Concurrent Connections",
			systemAdmin: "Unlimited",
			groupAdmin: "20",
			member: "5",
		},
	],
	"api-keys": [
		{
			service: "OpenAI API",
			systemAdmin: true,
			groupAdmin: true,
			member: true,
		},
		{
			service: "GitHub API",
			systemAdmin: true,
			groupAdmin: true,
			member: false,
		},
		{
			service: "Code Execution API",
			systemAdmin: true,
			groupAdmin: true,
			member: true,
		},
		{
			service: "Documentation Search API",
			systemAdmin: true,
			groupAdmin: true,
			member: true,
		},
		{
			service: "GitLab API",
			systemAdmin: true,
			groupAdmin: false,
			member: false,
		},
	],
	"code-execution": [
		{
			environment: "Python 3.11",
			languages: "Python",
			timeout: "30s",
			memory: "512 MB",
			status: "Active",
		},
		{
			environment: "Node.js 20",
			languages: "JavaScript, TypeScript",
			timeout: "30s",
			memory: "512 MB",
			status: "Active",
		},
		{
			environment: "Java 17",
			languages: "Java",
			timeout: "60s",
			memory: "1 GB",
			status: "Active",
		},
		{
			environment: "Go 1.21",
			languages: "Go",
			timeout: "30s",
			memory: "512 MB",
			status: "Active",
		},
		{
			environment: "Rust 1.72",
			languages: "Rust",
			timeout: "60s",
			memory: "1 GB",
			status: "Inactive",
		},
	],
	security: [
		{
			setting: "Two-Factor Authentication",
			value: "Required",
			scope: "System Admin, Group Admin",
			enforced: true,
		},
		{
			setting: "Password Complexity",
			value: "High (12+ chars, special)",
			scope: "All Users",
			enforced: true,
		},
		{
			setting: "Session Timeout",
			value: "30 minutes",
			scope: "All Users",
			enforced: true,
		},
		{
			setting: "IP Whitelist",
			value: "Enabled",
			scope: "Super Admin",
			enforced: true,
		},
		{
			setting: "Rate Limiting",
			value: "100 req/min",
			scope: "All Users",
			enforced: true,
		},
	],
	"change-history": [
		{
			time: "2025-10-16 14:32:15",
			user: "admin@devchat.com",
			action: "Updated Role",
			target: "user@example.com",
			changes: "Role: Group Admin → System Admin",
			ip: "192.168.1.100",
		},
		{
			time: "2025-10-16 13:15:42",
			user: "admin@devchat.com",
			action: "Enabled Feature",
			target: "developer@devchat.com",
			changes: "Code Execution: Disabled → Enabled",
			ip: "192.168.1.100",
		},
		{
			time: "2025-10-16 11:20:18",
			user: "superadmin@devchat.com",
			action: "Disabled Feature",
			target: "guest@devchat.com",
			changes: "AI Assistant: Enabled → Disabled",
			ip: "192.168.1.50",
		},
		{
			time: "2025-10-16 09:45:30",
			user: "admin@devchat.com",
			action: "Updated Limit",
			target: "team@devchat.com",
			changes: "AI Requests: 100/day → 200/day",
			ip: "192.168.1.100",
		},
		{
			time: "2025-10-15 16:20:45",
			user: "moderator@devchat.com",
			action: "Added API Key",
			target: "GitHub API",
			changes: "Status: Inactive → Active",
			ip: "192.168.1.75",
		},
	],
};
