name: Dev Chat CI
on:
  push:
    branches:
      - deploy

  workflow_dispatch:

env:
  REPO_ID: devchat-web
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_ID }}:latest , ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_ID }}:${{ steps.commit.outputs.short }}

  deploy:
    needs: build-and-push-docker
    runs-on: self-hosted
    steps:
      - name: Deploy to Server
        run: |
          cd ~/devchat &&
          docker compose pull web &&
          docker compose up -d web
