name: Create pull request when main branch is updated
on:
  push:
    branches:
      - main

env:
  REPO_ID: devchat-web

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/longlt201203/${{ env.REPO_ID }}/pulls \
          -d '{"title":"Deploy dev","body":"Deploy to dev server trigged by github ci","head":"${{ github.actor }}:main","base":"deploy"}'
